fix: missing host class in batteries (#606)
With PR #605 standalone homes have a host identity. This caused the
check to pass even though the host has no class causing the unfree
battery to fail with the following error:
```
       error: attribute 'class' missing
       at /nix/store/wnv7bc1psj89ylp29z3kabkbpwja0npn-source/modules/aspects/batteries/unfree/unfree.nix:44:28:
           43|           && host != null
           44|           && builtins.elem host.class validClasses
             |                            ^
           45|         ) { ${host.class}.unfree.packages = allowed-names; };
```
This PR changes a host existence check to the availability of its class.